# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on: 
  push:
    tags:
    - '*'
  
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
        
      - name: Build projects
        run: mvn -B clean install --file pom.xml

      - name: Rename and move artifacts based on OS
        shell: bash
        run: |
          mv target/TicTacToe-*.jar target/TicTacToe-${{matrix.os}}.jar
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: myArtifacts
          path: target/TicTacToe-*.jar
   
  release:

    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Create GitHub Release with all artifacts
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.TICTACTOE }}
          artifacts: "myArtifacts/TicTacToe-*.jar"
